django_mall/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from django_mall import views

import xadmin
xadmin.autodiscover()

# The version module automatically registers models that require version control
from xadmin.plugins import xversion
xversion.register_models()


urlpatterns = [
    # Django's own background management
    url(r'^admin/', admin.site.urls),
    # xadmin configuration
    url(r'xadmin/', include(xadmin.site.urls)),
    url(r'^$', views.index, name='index'),
    # Commodity part
    url(r'^mall/', include('mall.urls', namespace='mall')),
    # User account module
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # System module
    url(r'^sys/', include('system.urls', namespace='system')),
    # Personal center
    url(r'^m/', include('mine.urls', namespace='mine')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mall/urls.py
from django.conf.urls import url

from mall import views

urlpatterns = [
    # 商品列表 def function 来实现
    # url(r'^prod/list/$', views.product_list, name='product_list'),
    # 使用class 来实现
    url(r'^prod/list/$', views.ProductList.as_view(), name='product_list'),
    # 加载HTML片段的地址
    url(r'^prod/load/list/$', views.ProductList.as_view(
        template_name='product_load_list.html'
    ), name='product_load_list'),
    # 商品详情
    url(r'^prod/detail/(?P<pk>\S+)/$', views.product_detail, name='product_detail'),
    # 商品分类
    url(r'^prod/classify/$', views.prod_classify, name='prod_classify'),
]

mine/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from mine import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # order details
    url(r'^order/detail/(?P<sn>\S+)/$', login_required(views.OrderDetailView.as_view()), name='order_detail'),
    # Add to cart
    url(r'^cart/add/(?P<prod_uid>\S+)/$', views.cart_add, name='cart_add'),
    # my shopping cart
    url(r'^cart/$', views.cart, name='cart'),
    # Submit Order
    url(r'^order/pay/$', views.order_pay, name='order_pay'),
    # My order list
    url(r'^order/list/$', login_required(views.OrderListView.as_view()), name='order_list'),
    # my collection
    url(r'^prod/collect/$', views.prod_collect, name='prod_collect'),
]

mall/models.py
import uuid

from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor.fields import RichTextField
from django.db.models import F

from accounts.models import User
from system.models import ImageFile
from utils import constants


class Classify(models.Model):
    """ Classification of goods """
    uid = models.UUIDField('classify_ID', default=uuid.uuid4, editable=True)
    parent = models.ForeignKey('self', related_name='children', null=True, blank=True)
    img = models.ImageField('classify_image', upload_to='classify')
    code = models.CharField('code', max_length=32, null=True, blank=True)
    name = models.CharField('name', max_length=64)
    desc = models.CharField('description', max_length=64, null=True, blank=True)
    reorder = models.SmallIntegerField('reorder', default=0)
    is_valid = models.BooleanField('is_valid', default=True)

    created_at = models.DateTimeField('create_time', auto_now_add=True)
    updated_at = models.DateTimeField('update_time', auto_now=True)

    class Meta:
        db_table = 'mall_classify'
        verbose_name = 'goods_classification'
        verbose_name_plural = 'goods_classification'
        ordering = ['-reorder']

    def __str__(self):
        return '{}:{}'.format(self.code, self.name)


class Tag(models.Model):
    """ Product tags """

    uid = models.UUIDField('tag_id', default=uuid.uuid4, editable=True)
    img = models.ImageField('main_image', upload_to='tags', null=True, blank=True)
    code = models.CharField('code', max_length=32, null=True, blank=True)
    name = models.CharField('name', max_length=12)
    reorder = models.SmallIntegerField('reorder', default=0)
    is_valid = models.BooleanField('is_valid', default=True)

    created_at = models.DateTimeField('create_time', auto_now_add=True)
    updated_at = models.DateTimeField('modify_time', auto_now=True)

    class Meta:
        db_table = 'mall_tag'
        verbose_name = 'product tags'
        verbose_name_plural = 'product tags'
        ordering = ['-reorder']

    def __str__(self):
        return '{}:{}'.format(self.code, self.name)


class Product(models.Model):
    """ product """
    uid = models.UUIDField('product_id', default=uuid.uuid4, editable=False)
    name = models.CharField('product name', max_length=128)
    desc = models.CharField('product description', max_length=256, null=True, blank=True)
    # content = models.TextField('product description')
    # Rich text
    content = RichTextField('product details')

    types = models.SmallIntegerField('product type',
                                     choices=constants.PRODUCT_TYPES_CHOICES,
                                     default=constants.PRODUCT_TYPE_ACTUAL)
    price = models.IntegerField('Exchange price (point exchange)')
    origin_price = models.FloatField('original price')
    img = models.ImageField('main image', upload_to='%Y%m/product')
    buy_link = models.CharField('Purchase link', max_length=256, null=True, blank=True)
    reorder = models.SmallIntegerField('reorder', default=0)
    status = models.SmallIntegerField('Commodity status', default=constants.PRODUCT_STATUS_LOST,
                                      choices=constants.PRODUCT_STATUS_CHOICES)

    sku_count = models.IntegerField('in stock', default=0)
    ramain_count = models.IntegerField('Remaining stock', default=0)
    view_count = models.IntegerField('view count', default=0)
    score = models.FloatField('product rating', default=10.0)

    is_valid = models.BooleanField('is_valid', default=True)

    created_at = models.DateTimeField('create_time', auto_now_add=True)
    updated_at = models.DateTimeField('update_time', auto_now=True)

    tags = models.ManyToManyField(Tag, verbose_name='tags',
                                  related_name='tags',
                                  null=True,
                                  blank=True
                                  )
    classes = models.ManyToManyField(Classify,
                                     verbose_name='classification',
                                     related_name='classes',
                                     null=True,
                                     blank=True)

    banners = GenericRelation(ImageFile, verbose_name='banner image',
                              related_query_name='banners')

    class Meta:
        db_table = 'mall_product'
        verbose_name = 'product information'
        verbose_name_plural = 'product information'
        ordering = ['-reorder']

    def update_store_count(self, count):
        """
        Change product inventory information
        :param count:
        :return:
        """
        self.ramain_count = F('ramain_count') - abs(count)
        self.save()
        self.refresh_from_db()

    def __str__(self):
        return self.name

mall/forms.py
from django import forms

from mall.models import Product


class ProductAdminForm(forms.ModelForm):
    """ 商品编辑 """

    class Meta:
        model = Product
        exclude = ['created_at', 'updated_at']
        widgets = {
            # 修改表单的输入界面（下拉，radio）
            'types': forms.RadioSelect
        }

    def clean_price(self):
        """ 验证商品的价格 """
        price = self.cleaned_data['price']
        if int(price) <= 0:
            raise forms.ValidationError('销售价格不能小于0')
        return price

mall/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.generic import ListView

from mall.models import Product
from utils import constants


def product_list(request, template_name='product_list.html'):
    """ Product list """
    prod_list = Product.objects.filter(
        status=constants.PRODUCT_STATUS_SELL,
        is_valid=True)
    # Search by name
    name = request.GET.get('name', '')
    if name:
        prod_list = prod_list.filter(name__icontains=name)
    return render(request, template_name, {
        'prod_list': prod_list
    })


def product_detail(request, pk, template_name='product_detail.html'):
    """ product details """
    prod_obj = get_object_or_404(Product, uid=pk, is_valid=True)
    # User's default address
    user = request.user
    default_addr = None
    if user.is_authenticated:
        default_addr = user.default_addr
    return render(request, template_name, {
        'prod_obj': prod_obj,
        'default_addr': default_addr
    })


class ProductList(ListView):
    """" Product list """
    # How many pieces of data to put on each page
    paginate_by = 6
    # Template location
    template_name = 'product_list.html'

    def get_queryset(self):
        query = Q(status=constants.PRODUCT_STATUS_SELL,
                  is_valid=True)
        # Search by name
        name = self.request.GET.get('name', '')
        if name:
            query = query & Q(name__icontains=name)

        # Search by label
        tag = self.request.GET.get('tag', '')
        if tag:
            query = query & Q(tags__code=tag)

        # Search by category
        cls = self.request.GET.get('cls', '')
        if cls:
            query = query & Q(classes__code=cls)
        return Product.objects.filter(query)

    def get_context_data(self, **kwargs):
        """ Add variables to the context """
        context = super().get_context_data(**kwargs)
        context['params'] = self.request.GET.dict()
        return context


def prod_classify(request):
    """ Categories """
    return render(request, 'prod_classify.html', {

    })

mine/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import F, Sum, Q
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, ListView

from mall.models import Product
from mine.models import Order, Cart
from utils import constants, tools


@login_required
def index(request):
    """ Personal Center Homepage """
    return render(request, 'mine.html', {
        'constants': constants
    })


class OrderDetailView(DetailView):
    """ order details """
    model = Order
    slug_field = 'sn'
    slug_url_kwarg = 'sn'
    template_name = 'order_info.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['constants'] = constants
        return context


@login_required
@transaction.atomic()
def cart_add(request, prod_uid):
    """ Add product to cart Write interface """
    user = request.user
    product = get_object_or_404(Product, uid=prod_uid,
                                is_valid=True,
                                status=constants.PRODUCT_STATUS_SELL)
    # Purchase quantity
    count = int(request.POST.get('count', 1))
    # Check inventory
    if product.ramain_count < count:
        return HttpResponse('no')
    # Reduce inventory
    product.update_store_count(count)
    # Generate shopping cart record
    # If it has been added to the shopping cart, update the purchase quantity and price
    try:
        cart = Cart.objects.get(product=product, user=user,
                                status=constants.ORDER_STATUS_INIT)
        # Update price and quantity
        count = cart.count + count
        cart.count = count
        cart.amount = count * cart.price
        cart.save()
    except Cart.DoesNotExist:
        # Has not been added to the shopping cart
        Cart.objects.create(
            product=product,
            user=user,
            name=product.name,
            img=product.img,
            price=product.price,
            origin_price=product.origin_price,
            count=count,
            amount=count * product.price
        )
    return HttpResponse('ok')


@login_required
def cart(request):
    """ my shopping cart """
    user = request.user
    # List of items in my shopping cart
    prod_list = user.carts.filter(status=constants.ORDER_STATUS_INIT)
    # Aggregate query
    if request.method == 'POST':
        # Submit Order
        # 1.Save a snapshot of the user's address
        default_addr = user.default_addr
        if not default_addr:
            # notification
            messages.warning(request, 'Please select address information')
            return redirect('accounts:address_list')
        # Order total calculation
        cart_total = prod_list.aggregate(sum_amount=Sum('amount'),
                                         sum_count=Sum('count'))
        order = Order.objects.create(
            user=user,
            sn=tools.gen_trans_id(),
            buy_amount=cart_total['sum_amount'],
            buy_count=cart_total['sum_count'],
            to_user=default_addr.username,
            to_area=default_addr.get_region_format(),
            to_address=default_addr.address,
            to_phone=default_addr.phone
        )
        # 2.Modify the status in the cart
        # 3.Generate order, connect to shopping cart
        prod_list.update(
            status=constants.ORDER_STATUS_SUBMIT,
            order=order
        )
        # 4.Jump to order details
        messages.success(request, 'The order is successful, please pay')
        return redirect('mine:order_detail', order.sn)

    return render(request, 'cart.html', {
        'prod_list': prod_list
    })


@login_required
def order_pay(request):
    """ Submit Order """
    user = request.user
    if request.method == 'POST':
        sn = request.POST.get('sn', None)
        # 1.Query order information
        order = get_object_or_404(Order, sn=sn, user=user,
                                  status=constants.ORDER_STATUS_SUBMIT)
        # 2.Verify that the money is enough
        if order.buy_amount > user.integral:
            messages.error(request, 'Insufficient credit balance')
            return redirect('mine:order_detail', sn=sn)
        # 3.Money deducted
        user.ope_integral_account(0, order.buy_amount)
        # 4.Modify order status
        order.status = constants.ORDER_STATUS_PAIED
        order.save()
        # 5.Modify the status of the shopping cart association
        order.carts.all().update(status=constants.ORDER_STATUS_PAIED)
        messages.success(request, 'payment successful')
    return redirect('mine:order_detail', sn=sn)


@login_required
def order_list(request):
    """ My order list """
    status = request.GET.get('status', '')
    try:
        status = int(status)
    except ValueError:
        status = ''
    # 1.Query order data
    # 2.Pagination
    return render(request, 'order_list.html', {
        'constants': constants,
        'status': status
    })


# class-based
class OrderListView(ListView):
    """ Order list based on class view """
    model = Order
    template_name = 'order_list.html'

    def get_queryset(self):
        """ checking order """
        status = self.request.GET.get('status', '')
        user = self.request.user
        query = Q(user=user)
        if status:
            query = query & Q(status=status)
        return Order.objects.filter(query).exclude(
            status=constants.ORDER_STATUS_DELETED
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        status = self.request.GET.get('status', '')
        try:
            status = int(status)
        except ValueError:
            status = ''
        context['constants'] = constants
        context['status'] = status
        return context



@login_required
def prod_collect(request):
    """ my collection """
    return render(request, 'prod_collect.html')

mall/templates/address_edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>编辑地址</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, user-scalable=no"
    />
    <meta name="description" content="" />
    <link rel="stylesheet" href="lib/weui.min.css" />
    <link rel="stylesheet" href="css/jquery-weui.css" />
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body ontouchstart class="container">
    <!--主体-->
    <header class="wy-header">
      <div class="wy-header-icon-back"><span></span></div>
      <div class="wy-header-title">编辑地址</div>
    </header>
    <div class="weui-content">
      <div class="weui-cells weui-cells_form wy-address-edit">
        <div class="weui-cell">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">收货人</label>
          </div>
          <div class="weui-cell__bd">
            <input
              class="weui-input"
              type="text"
              placeholder="张三"
            />
          </div>
        </div>
        <div class="weui-cell">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">手机号</label>
          </div>
          <div class="weui-cell__bd">
            <input
              class="weui-input"
              type="number"
              pattern="[0-9]*"
              placeholder="13011112222"
            />
          </div>
        </div>
        <div class="weui-cell">
          <div class="weui-cell__hd">
            <label for="name" class="weui-label wy-lab">所在地区</label>
          </div>
          <div class="weui-cell__bd">
            <input
              class="weui-input"
              id="address"
              type="text"
              value="广东省 广州市 天河区"
              readonly=""
              data-code="420106"
              data-codes="420000,420100,420106"
            />
          </div>
        </div>
        <div class="weui-cell">
          <div class="weui-cell__hd">
            <label class="weui-label wy-lab">详细地址</label>
          </div>
          <div class="weui-cell__bd">
            <textarea
              class="weui-textarea"
              placeholder="珠江新城珠江大厦8楼"
            ></textarea>
          </div>
        </div>
        <div class="weui-cell weui-cell_switch">
          <div class="weui-cell__bd">设为默认地址</div>
          <div class="weui-cell__ft">
            <input class="weui-switch" type="checkbox" />
          </div>
        </div>
      </div>
      <div class="weui-btn-area">
        <a
          class="weui-btn weui-btn_primary"
          href="javascript:"
          id="showTooltips"
          >保存此地址</a
        >
        <a href="javascript:;" class="weui-btn weui-btn_warn">删除此地址</a>
      </div>
    </div>

    <script src="lib/jquery-2.1.4.js"></script>
    <script src="lib/fastclick.js"></script>
    <script type="text/javascript" src="js/jquery.Spinner.js"></script>
    <script>
      $(function() {
        FastClick.attach(document.body);
      });
    </script>

    <script src="js/jquery-weui.js"></script>
    <script src="js/city-picker.js"></script>
    <script>
      $('#address').cityPicker({
        title: '选择出发地',
        onChange: function(picker, values, displayValues) {
          console.log(values, displayValues);
        }
      });
    </script>
  </body>
</html>

mall/templates/address_list.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>地址管理</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<meta name="description" content="">
<link rel="stylesheet" href="lib/weui.min.css">
<link rel="stylesheet" href="css/jquery-weui.css">
<link rel="stylesheet" href="css/style.css">
</head>
<body ontouchstart class="container">
<!--主体-->
<header class="wy-header">
  <div class="wy-header-icon-back"><span></span></div>
  <div class="wy-header-title">地址管理</div>
</header>
<div class="weui-content">
  <div class="weui-panel address-box">
    <div class="weui-panel__bd">
      <div class="weui-media-box weui-media-box_text address-list-box">
        <a href="address_edit.html" class="address-edit"></a>
        <h4 class="weui-media-box__title"><span>张三</span><span>130****2000</span></h4>
        <p class="weui-media-box__desc address-txt">广东省广州市天河区珠江新城珠江大厦8楼</p>
        <span class="default-add">默认地址</span>
      </div>
    </div>
    <div class="weui-panel__bd">
      <div class="weui-media-box weui-media-box_text address-list-box">
        <a href="address_edit.html" class="address-edit"></a>
        <h4 class="weui-media-box__title"><span>张三</span><span>130****2000</span></h4>
        <p class="weui-media-box__desc address-txt">广东省广州市天河区珠江新城珠江大厦8楼</p>
      </div>
    </div>
    <div class="weui-panel__bd">
      <div class="weui-media-box weui-media-box_text address-list-box">
        <a href="address_edit.html" class="address-edit"></a>
        <h4 class="weui-media-box__title"><span>张三</span><span>130****2000</span></h4>
        <p class="weui-media-box__desc address-txt">广东省广州市天河区珠江新城珠江大厦8楼</p>
      </div>
    </div>
    <div class="weui-panel__bd">
      <div class="weui-media-box weui-media-box_text address-list-box">
        <a href="address_edit.html" class="address-edit"></a>
        <h4 class="weui-media-box__title"><span>张三</span><span>130****2000</span></h4>
        <p class="weui-media-box__desc address-txt">广东省广州市天河区珠江新城珠江大厦8楼</p>
      </div>
    </div>
    
  </div>
  <div class="weui-btn-area">
    <a class="weui-btn weui-btn_primary" href="address_edit.html" id="showTooltips">添加收货地址</a>
  </div>
</div>

<script src="lib/jquery-2.1.4.js"></script> 
<script src="lib/fastclick.js"></script> 
<script type="text/javascript" src="js/jquery.Spinner.js"></script>
<script>
  $(function() {
    FastClick.attach(document.body);
  });
</script>
<script src="js/jquery-weui.js"></script>
</body>
</html>

mall/templates/product_list.html
{% extends 'base.html' %}
{% block title %}
<title>product list</title>
{% endblock %}
{% block container %}
<!--top search-->
<header class='weui-header fixed-top'>
  <div class="weui-search-bar" id="searchBar">
    <form class="weui-search-bar__form" method="get" action=".">
      <div class="weui-search-bar__box">
        <i class="weui-icon-search"></i>
        <input type="search" class="weui-search-bar__input"
               id="searchInput"
               name="name"
               placeholder="Search for the product you want" required>
        <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
      </div>
      <label class="weui-search-bar__label" id="searchText" style="transform-origin: 0px 0px 0px; opacity: 1; transform: scale(1, 1);">
        <i class="weui-icon-search"></i>
        <span>Search for the product you want</span>
      </label>
    </form>
    <a href="javascript:" class="weui-search-bar__cancel-btn" id="searchCancel">cancel</a>
  </div>
  <div class="pro-sort">
    <div class="weui-flex">
      <div class="weui-flex__item"><div class="placeholder NormalCss">Comprehensive</div></div>
      <div class="weui-flex__item"><div class="placeholder SortAscCss">By sales</div></div>
      <div class="weui-flex__item"><div class="placeholder SortDescCss">By price</div></div></div>
    </div>
  </div>
</header>
<!--main body-->
<div class="weui-content" style="padding-top:85px;">
  <!--Product list-sliding load-->
  <div class="weui-pull-to-refresh__layer">
    <div class='weui-pull-to-refresh__arrow'></div>
    <div class='weui-pull-to-refresh__preloader'></div>
    <div class="down">Pull down to refresh</div>
    <div class="up">Release refresh</div>
    <div class="refresh">Refreshing</div>
  </div>
  <div id="list" class='demos-content-padded proListWrap'>

  </div>
  <div class="weui-loadmore" id="loading">
    <i class="weui-loading"></i>
    <span class="weui-loadmore__tips">loading</span>
  </div>
 
  
</div>

{% endblock %}
{% block footer %}
<script>
    var loading = false;  // loading or not
    var page = 1; // current page
    var noMore = false; // Is there a next page
    /**
     * Encapsulate function, fetch data asynchronously
     * @param callback
     */
    function loadData(callback) {
        if(loading) return;
        if(noMore) return;
        loading = true;
        $('#loading').show();
        $.ajax({
            url: '{% url 'mall:product_load_list' %}',
            data: {
                page: page,
                name: "{{ params.name|default_if_none:'' }}",
                cls: "{{ params.cls|default_if_none:'' }}",
                tag: "{{ params.tag|default_if_none:'' }}"
            },
            success: function(rest) {
                // Add HTML fragments to the content area
                $('#list').append(rest);
                page++;  // Page number plus 1
                loading = false;
                $('#loading').hide()
                // If there is a callback function, then call
                if (callback) {
                    callback()
                }
            }
        })
    }
      $(document.body).pullToRefresh().on("pull-to-refresh", function() {
          $("#list").empty();
          page = 1;
          noMore = false;
          loadData(function () {
              $(document.body).pullToRefreshDone();
          })
      });
      // infinite

      $(document.body).infinite(200).on("infinite", function() {
        loadData(); // Download Data
      });
      loadData();//The first page is loaded by default
</script>
{% endblock %}

mall/templates/product_load_list.html
{% for item in object_list %}
<div class="pro-items">
  <a href="{% url 'mall:product_detail' item.uid %}" class="weui-media-box weui-media-box_appmsg">
    <div class="weui-media-box__hd">
        <img class="weui-media-box__thumb" src="{{ item.img.url }}" alt="">
    </div>
    <div class="weui-media-box__bd">
      <h1 class="weui-media-box__desc">{{ item.name }}</h1>
      <div class="wy-pro-pri">$<em class="num font-15">{{ item.price }}</em></div>
      <ul class="weui-media-box__info prolist-ul">
        <li class="weui-media-box__info__meta"><em class="num">0 </em>comments</li>
        <li class="weui-media-box__info__meta"><em class="num">100% </em>thumps up</li>
      </ul>
    </div>
  </a>
</div>
{% endfor %}