accounts/urls.py
from django.conf.urls import url

from accounts import views

urlpatterns = [
    # User login
    url(r'^user/login/$', views.user_login, name='user_login'),
    # User exit
    url(r'^user/logout/$', views.user_logout, name='user_logout'),
    # User registration
    url(r'^user/register/$', views.user_register, name='user_register'),

    # Address list
    url(r'^user/address/list/$', views.address_list, name='address_list'),
    # Address modification and editing
    # user/address/edit/add/   user/address/edit/12/
    url(r'^user/address/edit/(?P<pk>\S+)/$', views.address_edit, name='address_edit'),
    url(r'^user/address/delete/(?P<pk>\d+)/$', views.address_delete, name='address_delete'),
]

django_mall/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from django_mall import views

import xadmin
xadmin.autodiscover()

# The version module automatically registers models that require version control
from xadmin.plugins import xversion
xversion.register_models()


urlpatterns = [
    # Django's own background management
    url(r'^admin/', admin.site.urls),
    # xadmin configuration
    url(r'xadmin/', include(xadmin.site.urls)),
    url(r'^$', views.index, name='index'),
    # Commodity part
    url(r'^mall/', include('mall.urls', namespace='mall')),
    # User account module
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # System module
    url(r'^sys/', include('system.urls', namespace='system')),
    # Personal center
    url(r'^m/', include('mine.urls', namespace='mine')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mall/urls.py
from django.conf.urls import url

from mall import views

urlpatterns = [
    # 商品列表 def function 来实现
    # url(r'^prod/list/$', views.product_list, name='product_list'),
    # 使用class 来实现
    url(r'^prod/list/$', views.ProductList.as_view(), name='product_list'),
    # 加载HTML片段的地址
    url(r'^prod/load/list/$', views.ProductList.as_view(
        template_name='product_load_list.html'
    ), name='product_load_list'),
    # 商品详情
    url(r'^prod/detail/(?P<pk>\S+)/$', views.product_detail, name='product_detail'),
    # 商品分类
    url(r'^prod/classify/$', views.prod_classify, name='prod_classify'),
]

mine/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from mine import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # order details
    url(r'^order/detail/(?P<sn>\S+)/$', login_required(views.OrderDetailView.as_view()), name='order_detail'),
    # Add to cart
    url(r'^cart/add/(?P<prod_uid>\S+)/$', views.cart_add, name='cart_add'),
    # my shopping cart
    url(r'^cart/$', views.cart, name='cart'),
    # Submit Order
    url(r'^order/pay/$', views.order_pay, name='order_pay'),
    # My order list
    url(r'^order/list/$', login_required(views.OrderListView.as_view()), name='order_list'),
    # my collection
    url(r'^prod/collect/$', views.prod_collect, name='prod_collect'),
]

system/urls.py
from django.conf.urls import url

from system import views

urlpatterns = [
    # news list
    url(r'^news/$', views.news_list, name='news_list'),
    # News details
    url(r'^new/(?P<pk>\d+)/$', views.news_detail, name='news_detail'),

    # verify code
    url(r'^verify/code/$', views.verify_code, name='verify_code'),
]

system/models.py
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db import models

from utils import constants


class Slider(models.Model):
    """ System carousel """
    name = models.CharField('name', max_length=32)
    desc = models.CharField('description', max_length=100, null=True, blank=True)
    types = models.SmallIntegerField('position',
                                     choices=constants.SLIDER_TYPES_CHOICES,
                                     default=constants.SLIDER_TYPE_INDEX)
    img = models.ImageField('image', upload_to='slider')
    reorder = models.SmallIntegerField('reorder', default=0, help_text='The higher the number, the higher the front')
    start_time = models.DateTimeField('start_time', null=True, blank=True)
    end_time = models.DateTimeField('end_time', null=True, blank=True)

    target_url = models.CharField('target url', max_length=255, null=True, blank=True)
    is_valid = models.BooleanField('delete or not', default=True)

    created_at = models.DateTimeField('create time', auto_now_add=True)
    updated_at = models.DateTimeField('update time', auto_now=True)

    class Meta:
        db_table = 'system_slider'
        verbose_name = 'slider'
        verbose_name_plural = 'slider'
        ordering = ['-reorder']


class News(models.Model):
    """ news and notification """
    types = models.SmallIntegerField('type', choices=constants.NEWS_TYPES_CHOICES,
                                     default=constants.NEWS_TYPE_NEW)
    title = models.CharField('title', max_length=255)
    content = models.TextField('contents')
    reorder = models.SmallIntegerField('reorder', default=0, help_text='The higher the number, the higher the front')
    start_time = models.DateTimeField('Effective start time', null=True, blank=True)
    end_time = models.DateTimeField('Effective end time', null=True, blank=True)
    view_count = models.IntegerField('views time', default=0)

    is_top = models.BooleanField('Whether to stick', default=False)
    is_valid = models.BooleanField('valid or not', default=True)

    created_at = models.DateTimeField('create time', auto_now_add=True)
    updated_at = models.DateTimeField('update time', auto_now=True)

    class Meta:
        db_table = 'system_news'
        verbose_name = 'news and notification'
        verbose_name_plural = 'news and notification'
        ordering = ['-reorder']


class ImageFile(models.Model):
    """ image """
    # 201902/xxxx
    img = models.ImageField('image_url', upload_to='%Y%m/images/')
    summary = models.CharField('image name', max_length=200)

    # Compound association
    content_type = models.ForeignKey(ContentType, null=True, blank=True)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    is_valid = models.BooleanField('valid or not', default=True)

    created_at = models.DateTimeField('create time', auto_now_add=True)
    updated_at = models.DateTimeField('update time', auto_now=True)

    class Meta:
        db_table = 'system_images'
        verbose_name = 'image table'
        verbose_name_plural = 'image table'

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, user-scalable=no"
    />
    <link rel="stylesheet" href="/static/lib/weui.min.css" />
    <link rel="stylesheet" href="/static/css/jquery-weui.css" />
    <link rel="stylesheet" href="/static/css/style.css" />
    {% block title %}
       <meta name="description" content=""/>
       <title>home page</title>
       {# Header information of the page, you can add header tags, css, js, <title>#}
    {% endblock %}
  </head>
  <body ontouchstart class="container">
    {% block container %}
     {# Content area of the page #}
    {% endblock %}



    <script src="/static/lib/jquery-2.1.4.js"></script>
    <script src="/static/lib/fastclick.js"></script>
    <script src="/static/js/jquery-weui.js"></script>
    <script>
        // Mobile event penetration
      $(function() {
        FastClick.attach(document.body);
      });
      // Return event
        $(".wy-header-icon-back").click(function () {
            history.go(-1);
        })
      {% if messages %}
          {% for msg in messages %}
            $.toptip('{{ msg }}', '{{ msg.tags }}');
          {% endfor %}
      {% endif %}
    </script>
    {% block footer %}
    {#   At the bottom of the page, can be used to put html fragments, you can add new js   #}
    {% endblock %}
  </body>
</html>

templates/footer.html
<!--bottom navigation-->
<div class="foot-black"></div>
<div class="weui-tabbar wy-foot-menu">
  <a href="{% url 'index' %}"
     class="weui-tabbar__item
    {% if tab == 'index' %}weui-bar__item--on {% endif %}">
    <div class="weui-tabbar__icon foot-menu-home"></div>
    <p class="weui-tabbar__label">home page</p>
  </a>
  <a href="{% url 'mall:prod_classify' %}"
     class="weui-tabbar__item
    {% if tab == 'classify' %}weui-bar__item--on {% endif %}">
    <div class="weui-tabbar__icon foot-menu-list"></div>
    <p class="weui-tabbar__label">classification</p>
  </a>
  <a href="{% url 'mine:cart' %}"
     class="weui-tabbar__item
    {% if tab == 'cart' %}weui-bar__item--on {% endif %}">
    <span
      class="weui-badge"
      style="position: absolute;top: -.4em;right: 1em;"
      >8</span
    >
    <div class="weui-tabbar__icon foot-menu-cart"></div>
    <p class="weui-tabbar__label">shopping cart</p>
  </a>
  <a href="{% url 'mine:index' %}"
     class="weui-tabbar__item
    {% if tab == 'mine' %}weui-bar__item--on {% endif %}">
    <div class="weui-tabbar__icon foot-menu-member"></div>
    <p class="weui-tabbar__label">mine</p>
  </a>
</div>

templates/index.html
{% extends 'base.html' %}
{% block title %}
    <title>Welcome to cosmetic ecommerce</title>
{% endblock %}
{% block container %}
    <header class="wy-header">
        <div class="wy-header-title">cosmetic ecommerce</div>
    </header>
    <!--top search-->
    <header class="weui-header">
        <div class="weui-search-bar" id="searchBar">
            <form class="weui-search-bar__form">
                <div class="weui-search-bar__box">
                    <i class="weui-icon-search"></i>
                    <input
                            type="search"
                            class="weui-search-bar__input"
                            id="searchInput"
                            placeholder="Search for the product you want"
                            required
                    />
                    <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
                </div>
                <label
                        class="weui-search-bar__label"
                        id="searchText"
                        style="transform-origin: 0px 0px 0px; opacity: 1; transform: scale(1, 1);"
                >
                    <i class="weui-icon-search"></i>
                    <span>Search for the product you want</span>
                </label>
            </form>
            <a
                    href="javascript:"
                    class="weui-search-bar__cancel-btn"
                    id="searchCancel"
            >cancel</a
            >
        </div>
    </header>
    {% if user.is_authenticated %}
        <h3>Welcome， {{ user.username }}</h3>
    {% else %}
        Welcome， <a href="{% url 'accounts:user_login' %}">sign in please</a>
    {% endif %}
    <!--main body-->
    <div class="weui-content">
        <!--top slider-->
        <div class="swiper-container swiper-banner">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <a href="../mall/templates/pro_info.html"><img src="/medias/upload/slider1.jpg"/></a>
                </div>
                <div class="swiper-slide">
                    <a href="../mall/templates/pro_info.html"><img src="/medias/upload/slider2.jpg"/></a>
                </div>
                <div class="swiper-slide">
                    <a href="../mall/templates/pro_info.html"><img src="/medias/upload/slider3.jpg"/></a>
                </div>
            </div>
            <div class="swiper-pagination"></div>
        </div>
        {#        <div class="swiper-container swiper-banner">#}
        {#            <div class="swiper-wrapper">#}
        {#                {% for slider in slider_list %}#}
        {#                    <div class="swiper-slide">#}
        {#                        <a href="{{ slider.target_url }}">#}
        {#                            <img src="{{ slider.img }}"/>#}
        {#                        </a>#}
        {#                    </div>#}
        {#                {% endfor %}#}
        {#            </div>#}
        {#            <div class="swiper-pagination"></div>#}
        {#        </div>#}
        <!--image classification-->
        <div class="weui-flex wy-iconlist-box">
            <div class="weui-flex__item">
                <a href="{% url 'mall:product_list' %}?tag=jxtj" class="wy-links-iconlist"
                >
                    <div class="img"><img src="/static/images/icon-link1.png"/></div>
                    <p>Special Recommendation</p></a
                >
            </div>
            <div class="weui-flex__item">
                <a href="{% url 'mall:product_list' %}?cls=jszc" class="wy-links-iconlist"
                >
                    <div class="img"><img src="/static/images/lipstick1.jpg"/></div>
                    <p>Lipstick Session</p></a
                >
            </div>
            <div class="weui-flex__item">
                <a href="all_orders.html" class="wy-links-iconlist"
                >
                    <div class="img"><img src="/static/images/icon-link3.png"/></div>
                    <p>Order Management</p></a
                >
            </div>
            <div class="weui-flex__item">
                <a href="javascript:alert('Under construction, do please expect')" class="wy-links-iconlist"
                >
                    <div class="img"><img src="/static/images/icon-link4.png"/></div>
                    <p>Join us</p></a
                >
            </div>
        </div>
        <!--news transformation-->
        <div class="wy-ind-news">
            <i class="news-icon-laba"></i>
            <div class="swiper-container swiper-news">
                <div class="swiper-wrapper">
                    {% for item in news_list %}
                        <div class="swiper-slide">
                            <a href="{% url 'system:news_detail' item.pk %}"
                            >{{ item.title }}</a
                            >
                        </div>
                    {% endfor %}
                </div>
                <div class="swiper-pagination"></div>
            </div>
            <a href="{% url 'system:news_list' %}" class="newsmore"
            ><i class="news-icon-more"></i
            ></a>
        </div>
        <!--special recommendation-->
        <div class="wy-Module">
            <div class="wy-Module-tit"><span>Sepecial Recommendation</span></div>
            <div class="wy-Module-con">
                <div
                        class="swiper-container swiper-jingxuan"
                        style="padding-top:34px;"
                >
                    <div class="swiper-wrapper">
                        {% for item in jx_list %}
                            <div class="swiper-slide">
                                <a href="{% url 'mall:product_detail' item.uid %}">
                                    <img src="{{ item.img.url }}"/>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="swiper-pagination jingxuan-pagination"></div>
                </div>
            </div>
        </div>
        <!--Lipstick Session-->
        <div class="wy-Module">
            <div class="wy-Module-tit"><span>Lipstick Session</span></div>
            <div class="wy-Module-con">
                <div
                        class="swiper-container swiper-jiushui"
                        style="padding-top:34px;"
                >
                    <div class="swiper-wrapper">
                        {% for item in js_list %}
                            <div class="swiper-slide">
                                <a href="{% url 'mall:product_detail' item.uid %}">
                                    <img src="{{ item.img.url }}"/>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="swiper-pagination jingxuan-pagination"></div>
                </div>
            </div>
        </div>
        <!--guess you like-->
        <div class="wy-Module">
            <div class="wy-Module-tit-line"><span>guess you like</span></div>
            <div class="wy-Module-con">
                <ul class="wy-pro-list clear">
                    <li>
                        <a href="../mall/templates/pro_info.html">
                            <div class="proimg"><img src="/static/upload/lipstick11.jpg"/></div>
                            <div class="protxt">
                                <div class="name">
                                    Seductive Sheers Lipstick 3.5g
                                </div>
                                <div class="wy-pro-pri">$<span>22.00</span></div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="../mall/templates/pro_info.html">
                            <div class="proimg"><img src="/static/upload/lipstick13.jpg"/></div>
                            <div class="protxt">
                                <div class="name">
                                    Reve De Miel Lip Stick (4g Stick)
                                </div>
                                <div class="wy-pro-pri">$<span>6.50</span></div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="../mall/templates/pro_info.html">
                            <div class="proimg"><img src="/static/upload/lip_liner11.jpg"/></div>
                            <div class="protxt">
                                <div class="name">
                                    Decay 24/7 Lip Pencil (Various Shades)
                                </div>
                                <div class="wy-pro-pri">$<span>11.20</span></div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="../mall/templates/pro_info.html">
                            <div class="proimg"><img src="/static/upload/lip_liner12.jpg"/></div>
                            <div class="protxt">
                                <div class="name">
                                    Lip Pencil (Various Shades)
                                </div>
                                <div class="wy-pro-pri">$<span>15.00</span></div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="../mall/templates/pro_info.html">
                            <div class="proimg"><img src="/static/upload/powder1.jpg"/></div>
                            <div class="protxt">
                                <div class="name">
                                    Real Techniques Powder Brush
                                </div>
                                <div class="wy-pro-pri">$<span>10.99</span></div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="../mall/templates/pro_info.html">
                            <div class="proimg"><img src="/static/upload/primer4.jpg"/></div>
                            <div class="protxt">
                                <div class="name">
                                    Bobbi Brown Vitamin Enriched Face Base 50ml
                                </div>
                                <div class="wy-pro-pri">$<span>44.50</span></div>
                            </div>
                        </a>
                    </li>
                </ul>
                <div class="morelinks"><a href="../mall/templates/product_list.html">search more >></a></div>
            </div>
        </div>
    </div>
    {#  包含底部的html模块 #}
    {% include 'footer.html' with tab='index' %}
{% endblock %}
{% block footer %}
    <script src="/static/js/swiper.js"></script>
    <script>
        $('.swiper-banner').swiper({
            loop: true,
            autoplay: 3000
        });
        $('.swiper-news').swiper({
            loop: true,
            direction: 'vertical',
            paginationHide: true,
            autoplay: 30000
        });
        $('.swiper-jingxuan').swiper({
            pagination: '.swiper-pagination',
            loop: true,
            paginationType: 'fraction',
            slidesPerView: 3,
            paginationClickable: true,
            spaceBetween: 2
        });
        $('.swiper-jiushui').swiper({
            pagination: '.swiper-pagination',
            paginationType: 'fraction',
            loop: true,
            slidesPerView: 3,
            slidesPerColumn: 2,
            paginationClickable: true,
            spaceBetween: 2
        });
    </script>
{% endblock %}